過去にいいねしたユーザに新規レビューをメール通知する機能
PB-193/Totono-ru pull request #87
Opened 2023-08-17 09:11 UTC by PB-193

### 概要
あるユーザが新規でレビューを投稿した時に、そのユーザの過去のレビューに対して「いいね」していたユーザに、メールで「ユーザが新しいレビューを投稿した」ことを、お知らせする機能を作成しました。

### 実装画面
![Aug-17-2023 18-10-41](https://github.com/PB-193/Totono-ru/assets/127069516/40ad94b8-3aa2-4601-81d4-fcc8c9fab6c7)

2023-08-21 10:43 UTC, ikedanoda requested changes
コメント確認お願いします！

2023-08-21 10:43 UTC, ikedanoda commented on app/models/content.rb
> +    after_create :send_message_to_favorited_users
ここafter_createを使うとテストデータ作成時にも処理が走ってしまうので、callbackを使わない形で呼び出しお願いします！

2023-08-21 10:43 UTC, ikedanoda commented on app/models/content.rb
> +    def send_message_to_favorited_users
こちらのメソッドのテストコード（spec）を記述お願いします！
※ spec書く過程でメソッドの中身に修正が入ってもOKです！

2023-08-22 06:12 UTC, PB-193 commented
池田様から頂いたコメントに対して、以下のコミットでコードを変更および修正いたしました。
お手数ですが、ご確認をお願いいたします。

2023-09-19 03:15 UTC, closed without merging